#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  hospital-network:
    external: true


services:
#---------------------------------------------------------------------------------------------------------------------------
# Single Orderer Setup
#---------------------------------------------------------------------------------------------------------------------------
  orderer.switch2logic.co.za:
    container_name: orderer.switch2logic.co.za
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/orderer/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/orderer/msp
      #TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/orderer/tls/ca.crt]
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts/:/etc/hyperledger/fabric/orderer/channel-artifacts
        - ./crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer.switch2logic.co.za/msp:/etc/hyperledger/fabric/orderer/msp
        - ./crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer.switch2logic.co.za/tls:/etc/hyperledger/fabric/orderer/tls
    networks:
      - hospital-network
    restart: always  

#---------------------------------------------------------------------------------------------------------------------------
# Hospital1 Network Setup
#---------------------------------------------------------------------------------------------------------------------------
  ca.hospital1.switch2logic.co.za:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.hospital1.switch2logic.co.za
      - FABRIC_CA_HOME=/etc/hyperledger/fabric/ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric/ca/ca.hospital1.switch2logic.co.za-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric/ca/892cd9320cf8bca575408d13127d52b6f4e87ec78be94f19fd9634c2706cd5ea_sk
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/ca/:/etc/hyperledger/fabric/ca   
    container_name: ca.hospital1.switch2logic.co.za
    networks:
      - hospital-network
    restart: always    

  peer0.hospital1.switch2logic.co.za:
    container_name: peer0.hospital1.switch2logic.co.za
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hospital1.switch2logic.co.za
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.hospital1.switch2logic.co.za:7051   
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital1.switch2logic.co.za:7051
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #State Database Config
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.hospital1.switch2logic.co.za:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls:/etc/hyperledger/fabric/tls
       # - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users:/etc/hyperledger/msp/users 
    networks:
      - hospital-network
    restart: always  

  couchdb.peer0.hospital1.switch2logic.co.za:
    container_name: couchdb.peer0.hospital1.switch2logic.co.za
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984   
    networks:
      - hospital-network
    restart: always  

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users/Admin@hospital1.switch2logic.co.za/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/server.key
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        #- ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
        - ./crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
        - ./channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts      
    networks:
        - hospital-network
    restart: always      
