NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.hospital2.switch2logic.co.za-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.hospital2.switch2logic.co.za-cert.pem
    OrganizationalUnitIdentifier: peer
